FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

RUN  npm run build

# ---------- SERVE STAGE ----------
FROM nginx:alpine

# Copy build output from Node stage
COPY --from=builder /app/dist /usr/share/nginx/html



EXPOSE 80 
CMD ["nginx", "-g", "daemon off;"]