version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: pern_db_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: perndb
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data
    networks:
      - local-network

  backend-api:
    build: ./backend
    container_name: pern_backend_local
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localpassword
      - POSTGRES_DB=perndb
      - DBPORT=5432
    volumes:
      - exam_uploads:/app/public/uploads    
    depends_on:
      - postgres-db
    networks:
      - local-network

  frontend-app:
    build: ./frontend
    container_name: pern_frontend_local
    ports:
      - "8080:80" # Maps localhost:8080 on your machine to container port 80
    depends_on:
      - backend-api
    networks:
      - local-network

volumes:
  pgdata_local:
  exam_uploads:

networks:
  local-network: